### ISSUE TITLE
Feature request: list the owners of the specified file

### ISSUE THREAD

**Issue by hax** [beaugunderson/codeowners#1]
```sh
$ codeowners of path/to/some/file
```

**Comment by beaugunderson** [comment]
excellent idea--i may not be able to implement for some time but am happy to merge a pull request if you have time :)

**Comment by ThisIsMissEm** [comment]
I can probably take a crack at implementing this tonight

**Comment by glensc** [comment]
for now, could use some shell scripting:

```
➜ npx codeowners audit | grep '^\.envrc '
.envrc                              @staff/teams/media
```
